<a href="https://colab.research.google.com/github/Arham-15/traffic-prediction-system/blob/dev/01_data_exploration_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("IntelliTraffic Data Exploration 🚦")

IntelliTraffic Data Exploration 🚦

In [7]:
file_path = "/content/Metro_Interstate_Traffic_Volume.csv.gz"

df = pd.read_csv(file_path)
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [8]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 48204
Columns: 9

In [9]:
df.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918

In [10]:
df.tail()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
48199,NaN,283.45,0.0,0.0,75,Clouds,broken clouds,2018-09-30 19:00:00,3543
48200,NaN,282.76,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 20:00:00,2781
48201,NaN,282.73,0.0,0.0,90,Thunderstorm,proximity thunderstorm,2018-09-30 21:00:00,2159
48202,NaN,282.09,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 22:00:00,1450
48203,NaN,282.12,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 23:00:00,954

In [11]:
df.columns

Index(['holiday', 'temp', 'rain_1h', 'snow_1h', 'clouds_all', 'weather_main',
       'weather_description', 'date_time', 'traffic_volume'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48204 entries, 0 to 48203
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   holiday              61 non-null     object
 1   temp                 48204 non-null  float64
 2   rain_1h              48204 non-null  float64
 3   snow_1h              48204 non-null  float64
 4   clouds_all           48204 non-null  int64
 5   weather_main         48204 non-null  object
 6   weather_description  48204 non-null  object
 7   date_time            48204 non-null  object
 8   traffic_volume       48204 non-null  int64
dtypes: float64(3), int64(2), object(4)
memory usage: 3.3+ MB

In [13]:
df.describe()

               temp       rain_1h       snow_1h    clouds_all  traffic_volume
count  48204.000000  48204.000000  48204.000000  48204.000000    48204.000000
mean     281.205870      0.334264      0.000222     49.362231     3259.818355
std       13.338232     44.789133      0.008168     39.015750     1986.860670
min        0.000000      0.000000      0.000000      0.000000        0.000000
25%      272.160000      0.000000      0.000000      1.000000     1193.000000
50%      282.450000      0.000000      0.000000     64.000000     3380.000000
75%      291.806000      0.000000      0.000000     90.000000     4933.000000
max      310.070000   9831.300000      0.510000    100.000000     7280.000000

In [14]:
df.isnull

<bound method DataFrame.isnull of       holiday    temp  rain_1h  snow_1h  clouds_all  weather_main  \
0         NaN  288.28      0.0      0.0          40        Clouds
1         NaN  289.36      0.0      0.0          75        Clouds
2         NaN  289.58      0.0      0.0          90        Clouds
3         NaN  290.13      0.0      0.0          90        Clouds
4         NaN  291.14      0.0      0.0          75        Clouds
...       ...     ...      ...      ...         ...           ...
48199     NaN  283.45      0.0      0.0          75        Clouds
48200     NaN  282.76      0.0      0.0          90        Clouds
48201     NaN  282.73      0.0      0.0          90  Thunderstorm
48202     NaN  282.09      0.0      0.0          90        Clouds
48203     NaN  282.12      0.0      0.0          90        Clouds

          weather_description            date_time  traffic_volume
0            scattered clouds  2012-10-02 09:00:00            5545
1               broken clouds  2012-10-02 10:00:00            4516
2             overcast clouds  2012-10-02 11:00:00            4767
3             overcast clouds  2012-10-02 12:00:00            5026
4               broken clouds  2012-10-02 13:00:00            4918
...                       ...                  ...             ...
48199           broken clouds  2018-09-30 19:00:00            3543
48200         overcast clouds  2018-09-30 20:00:00            2781
48201  proximity thunderstorm  2018-09-30 21:00:00            2159
48202         overcast clouds  2018-09-30 22:00:00            1450
48203         overcast clouds  2018-09-30 23:00:00             954

[48204 rows x 9 columns]>